version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      d3:
        patterns:
          - "d3-*"
          - "@types/d3-*"
      vitest:
        patterns:
          - "vitest"
      typescript:
        patterns:
          - "typescript"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
